Forgot to complete test smoke check

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -223,3 +223,10 @@ jobs:
               echo "Smoke test passed"
               exit 0
             fi
+
+            echo "Current status: ${status:-unreachable}"
+            sleep 5
+          done
+
+          echo "Smoke test failed"
+          exit 1
